### ISSUE TITLE
feature request: execute vs send

### ISSUE THREAD

**Issue by jedineeper** [Anssett/Aard-Plugins#1]
Could the tracker implementation use Execute instead of SendNoEcho here to allow for local processing of the tracker channel?

https://github.com/Anssett/Aard-Plugins/blob/main/FriendCheck.xml#L135

**Comment by Anssett** [comment]
It hits my tracker alias fine with SendNoEcho. I'm using Mendaloth's. Which tracker plugin are you using? I may have to reconsider how I handle this if other trackers rely on text being visible.

**Comment by jedineeper** [comment]
as discussed, not easily resolvable for all use cases in hindsight so #closed
