### ISSUE TITLE
Another can of worms... Immunities?

### ISSUE THREAD

**Issue by etchasletch** [Anssett/Aard-Plugins#10]
I notice that the "seekrep (target)" big blue deluge of info currently tracks the immunities, cause that's a part of seek. That's neat. More helpful might be a "not immune to" list. Might be smart to put something like that its own alias, or add a toggle on/off for an additional line send to echo/channel? Gotta be conscious that we don't build like 5 arguments per seekrep command.

**Comment by Anssett** [comment]
Yeah, I think in a future version I'll be able to do this sort of thing. Maybe even drop some of this stuff in a miniwindow "most recent seek target" or something, for quicker reference.
Ugh. miniwindow. Something else to learn lol.

**Comment by Anssett** [comment]
duplicate-ish of #4 
Longer term miniwindow idea is gonna be super back burnered
