### ISSUE TITLE
[WCC Helper] Add more visible notification when breath is expiring

### ISSUE THREAD

**Issue by Anssett** [Anssett/Aard-Plugins#15]
maybe at 10 secs remaining? 2 durability? something like that.

**Comment by etchasletch** [comment]
Capture and substitute the line re: durability to hack in current breath dura? [Durability -1]  -> [Durability left: 6/10] or something?

**Comment by Anssett** [comment]
Ok I did the substitute. I think. It installed properly, but I'll have to do a test run to verify ofc. Less confident on this than most of my fixes

**Comment by Anssett** [comment]
```
Like oil and water, the thin layer of ice particles around you buffet away

the microscopic shards of ice. 
[
1/10 Durability
]
```

well that needs fixing..

**Comment by Anssett** [comment]
Think it's mostly fixed. One more test.

**Comment by Anssett** [comment]
yay, it's working as expected now.
