### ISSUE TITLE
WCC Helper 'compact' / verbosity setting

### ISSUE THREAD

**Issue by etchasletch** [Anssett/Aard-Plugins#19]
Could hide the vortex pull message (i only ever notice it when i'm scrolling back thru a log, and i've got plenty of time then :P) and condense the status pings to a single line possibly? As suggested before it could read:

(WCC) Shards: (time) Vortex: (time) W:(whelps killed) V:(vortex killed) Breath: (time, durability)

And if you want to track eggs in there still, could go E: W: V:

Wyrm notices should probably be multi-line still, depending on the granularity of options you want you could consider the old single line.

**Comment by Anssett** [comment]
Ok, `wcc config verbose` has been added. Changes the output of the regular status notifications and removes the vortex pull notifications.
I'll leave this open a bit longer to see if anything else comes up that ought to be de-verbosed.

**Comment by Anssett** [comment]
Seems to be working. Feel free to add more commentary if you come across anything else needing to be quieted a bit.
