### ISSUE TITLE
WCC Helper wcc start unexpected arrival room

### ISSUE THREAD

**Issue by etchasletch** [Anssett/Aard-Plugins#20]
wcc start seems to touch rune;run 2n;look dragon;**run s2w**, instead of just run sw.

**Comment by Anssett** [comment]
yes it does :P by design, because that's just the direction i usually start myself lol. could possibly make this configurable too but that is a little trickier.

**Comment by etchasletch** [comment]
It takes you to a room with no egg?

**Comment by Anssett** [comment]
Yeah. It's a direct copy of the commands I stack when i start manually. Not claiming it is good or bad, just what it is. For some reason my brain decided to stop the speedwalk in an empty room.

**Comment by etchasletch** [comment]
Would you be opposed to a more neutral 'touch rune;run 2n;look dragon;run 2s'? I/anyone can also just stack it the way one likes, WCC start isn't required to enable the plugin anyway

**Comment by Anssett** [comment]
Not particularly opposed, no :)

**Comment by Anssett** [comment]
ok did the thing. wcc start now does touch rune;run 2n;l anxia;run 2s. Not intending on making this path configurable at the moment.
