### ISSUE TITLE
Delayed reminders of seek failing

### ISSUE THREAD

**Issue by etchasletch** [Anssett/Aard-Plugins#8]
Guessing once the plugin is stable enough, this message could probably go away entirely, but-
On a fixed delay, after getting "Your fail to seek your target correctly." (sic):

something broke. Or seek failed and you need to try again.

**Comment by Anssett** [comment]
Yeah, the 20 second thing is hardcoded into wrapped captures. Trying to find fiendish to see if we can have a version included at some point with an adjustable timer, but I don't have my hopes up either. So it's not actually a stability issue of SeekRep, but a combination of "git gud" with seek skill, and interaction with Fiendish's stuff.

**Comment by etchasletch** [comment]
Future or even current version may not need the 'oops something went wrong' message at all. Unless that's baked into the wrap capture function somehow. We'd know it failed by the standard seek-failed message- unless there's another issue that could crop up with the captures not closing quickly enough.

**Comment by Anssett** [comment]
Yeah. That is the output of the "wrapped capture took too long" function. I could have it do "nothing" but the underlying timer will always be there.

**Comment by Anssett** [comment]
closing as "won't fix" since this is kind of a Fiendish thing. Another few versions and I'll probably just remove the debugging "somethign broke" language.
