### ISSUE TITLE
Special case for 0 to all resists / none found?

### ISSUE THREAD

**Issue by etchasletch** [Anssett/Aard-Plugins#9]
https://mb.aardwolfboot.com/elexeviduf

Originally I was considering the case what should happen if mob has 0 resists, but this could probably occur with the top/bot filter as well. Just a stray 'Target' line isn't informative.

(Side note- change Target to "Seeking: a black cat"? "Seekrep: a black cat"?)

**Comment by Anssett** [comment]
Yeah, that's one of those outliers that I needed to be reminded exists :) I'm on the fence, currently, about how to display large quantities of "not so useful" data. In this case, no notable resist values. Do I add extra logic for "if all resist values == 0 then output 'this is a boring mob'"? Etc. Open to suggestions on clean ways to handle this :D

**Comment by Anssett** [comment]
I think this kind of ties into #13 - going to close this and move any comment/questions into that bit?
